import * as fs from "fs";
import * as path from "path";
import type { RouteResult } from "./types.ts";

export interface ApplyResult {
  targetDir: string;
  appliedSkills: string[];
  instructionsCopied: boolean;
  manifestWritten: boolean;
  errors: string[];
}

function copySkillDir(srcDir: string, destDir: string): void {
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    // Skip internal provenance files that consumers don't need
    if (entry.name === "UPSTREAM.md") continue;

    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);

    if (entry.isDirectory()) {
      copySkillDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

export function applySkills(
  result: RouteResult,
  targetDir = ".agents/skills",
  workspaceRoot: string = process.cwd(),
  packageRoot: string = workspaceRoot
): ApplyResult {
  const resolvedTarget = path.resolve(workspaceRoot, targetDir);
  const appliedSkills: string[] = [];
  const errors: string[] = [];

  if (!fs.existsSync(resolvedTarget)) {
    fs.mkdirSync(resolvedTarget, { recursive: true });
  }

  for (const skill of result.skills) {
    const srcDir = path.resolve(packageRoot, skill.path);
    const destDir = path.resolve(resolvedTarget, skill.name);

    if (!fs.existsSync(srcDir)) {
      errors.push(`Skill directory not found on disk: ${srcDir}`);
      continue;
    }

    try {
      copySkillDir(srcDir, destDir);
      appliedSkills.push(skill.name);
    } catch (err: any) {
      errors.push(`Failed to copy skill '${skill.name}': ${err.message}`);
    }
  }

  // Copy universal instructions
  let instructionsCopied = false;
  const srcInstructions = path.resolve(packageRoot, "instructions");
  const destInstructions = path.resolve(resolvedTarget, "..", "instructions");
  if (fs.existsSync(srcInstructions) && !fs.existsSync(destInstructions)) {
    try {
      fs.cpSync(srcInstructions, destInstructions, { recursive: true, force: true });
      instructionsCopied = true;
    } catch {
      // Non-fatal
    }
  }

  // Write manifest file (.agents/AGENTS.md)
  let manifestWritten = false;
  try {
    const manifestPath = path.resolve(resolvedTarget, "..", "AGENTS.md");
    const manifest = generateManifest(result, appliedSkills);
    fs.writeFileSync(manifestPath, manifest, "utf-8");
    manifestWritten = true;
  } catch {
    // Non-fatal
  }

  return {
    targetDir: resolvedTarget,
    appliedSkills,
    instructionsCopied,
    manifestWritten,
    errors
  };
}

function generateManifest(result: RouteResult, appliedSkills: string[]): string {
  const lines: string[] = [];
  const now = new Date().toISOString().split("T")[0];

  lines.push(`# AgentLayer Skills Manifest`);
  lines.push(``);
  lines.push(`> Generated by AgentLayer Smart Router on ${now}`);
  lines.push(`> Task: "${result.prompt}"`);
  lines.push(`> Confidence: ${(result.confidence * 100).toFixed(0)}%`);
  lines.push(``);
  lines.push(`## Installed Skills (${appliedSkills.length})`);
  lines.push(``);

  for (const skill of result.skills) {
    if (appliedSkills.includes(skill.name)) {
      lines.push(`### ${skill.name} (${skill.layer} layer)`);
      lines.push(`- **Rationale:** ${skill.reason}`);
      lines.push(`- **Path:** \`skills/${skill.name}/SKILL.md\``);
      lines.push(``);
    }
  }

  lines.push(`## Usage`);
  lines.push(``);
  lines.push(`These skills are loaded automatically by AI coding agents that support the \`.agents/skills/\` convention (Codex, Antigravity, Claude Code, Cursor).`);
  lines.push(``);
  lines.push(`To regenerate with different options:`);
  lines.push("```bash");
  lines.push(`npx agentlayer apply "${result.prompt}"`);
  lines.push("```");
  lines.push(``);

  return lines.join("\n");
}

export function bundleSkills(
  result: RouteResult,
  packageRoot: string = process.cwd(),
  includeInstructions = true
): string {
  const sections: string[] = [];

  sections.push(
    `# AgentLayer Skills Bundle\n\n` +
    `> **Task:** "${result.prompt}"\n` +
    `> **Confidence:** ${(result.confidence * 100).toFixed(0)}%\n` +
    `> **Selected Skills:** ${result.skills.map((s) => s.name).join(", ")}\n` +
    `> **Layers:** ${[...new Set(result.skills.map((s) => s.layer))].join(", ")}\n`
  );

  if (includeInstructions) {
    const instructionsDir = path.resolve(packageRoot, "instructions");
    if (fs.existsSync(instructionsDir)) {
      sections.push(`## Universal Engineering Instructions\n`);
      const files = fs.readdirSync(instructionsDir).filter((f) => f.endsWith(".md")).sort();
      for (const file of files) {
        const content = fs.readFileSync(path.join(instructionsDir, file), "utf-8");
        sections.push(`### ${file.replace(/\.md$/, "")}\n\n${content}\n`);
      }
    }
  }

  // Group skills by layer in bundle output
  const layerLabels: Record<string, string> = {
    process: "Process & Planning",
    domain: "Domain Knowledge",
    implementation: "Implementation & Architecture",
    risk: "Risk & Security Audit",
    verification: "Testing & Verification"
  };

  const layers = ["process", "domain", "implementation", "risk", "verification"];
  for (const layer of layers) {
    const layerSkills = result.skills.filter((s) => s.layer === layer);
    if (layerSkills.length === 0) continue;

    sections.push(`## ${layerLabels[layer] || layer}\n`);

    for (const skill of layerSkills) {
      const skillMdPath = path.resolve(packageRoot, skill.path, "SKILL.md");
      if (fs.existsSync(skillMdPath)) {
        const content = fs.readFileSync(skillMdPath, "utf-8");
        sections.push(`### ${skill.name}\n*Rationale: ${skill.reason}*\n\n${content}\n`);
      }
    }
  }

  return sections.join("\n---\n\n");
}
